name: Deploy KerjaIn Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /www/wwwroot/kerjaIn-backend

            # Pull the latest code
            git pull origin main

            # Install php dependencies
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

            # Run migrations
            php artisan migrate --force

            # Optimize Laravel
            php artisan optimize
